---
ID: "6410a89f-8ee3-4784-9b8e-76b87d0dbab4"
Parent: "50fcf4a0-1ac0-4594-bd47-b19401e61fee"
Template: "06193f29-ad7b-4340-8a2a-869cb17250cd"
Path: /sitecore/content/AXA/Intranet/Employee Benefits/Presentation/Page Designs/Default
DB: master
SharedFields:
- ID: "0966b999-0d0e-4278-acc9-9da69d461fe6"
  Hint: PartialDesigns
  Value: "{BB2C8928-776B-4376-8609-89513F27ED95}|{09B12F69-72D5-4B1B-AA29-53C79CB2511C}"
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:p="p" xmlns:s="s"
      p:p="1">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        s:l="{EC63A911-53A7-47A3-8374-D40CF5DE788D}" />
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190519T221612Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\virtualssuser
