---
ID: "ae18b94d-82a7-405f-b345-5972ee2289b7"
Parent: "816adaa8-6a5f-42d8-86c6-9e29eaefbc5d"
Template: "26fce9bf-0256-458d-8281-a713a5bf5520"
Path: /sitecore/content/AXA/Intranet/Employee Benefits/Presentation/Cache Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190519T221524Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\virtualssuser
